/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package supermarket;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Romil Chauhan
 */
public class CustomerBill extends javax.swing.JFrame {

    /**
     * Creates new form CustomerBill
     */
    public CustomerBill() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cb_table = new javax.swing.JTable();
        cb_total_price = new javax.swing.JLabel();
        cb_total_tprice = new javax.swing.JTextField();
        cb_done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Qty", "Price per product"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cb_table);
        if (cb_table.getColumnModel().getColumnCount() > 0) {
            cb_table.getColumnModel().getColumn(0).setMinWidth(70);
            cb_table.getColumnModel().getColumn(0).setPreferredWidth(70);
            cb_table.getColumnModel().getColumn(0).setMaxWidth(70);
            cb_table.getColumnModel().getColumn(1).setMinWidth(100);
            cb_table.getColumnModel().getColumn(1).setPreferredWidth(100);
            cb_table.getColumnModel().getColumn(1).setMaxWidth(100);
            cb_table.getColumnModel().getColumn(2).setMinWidth(60);
            cb_table.getColumnModel().getColumn(2).setPreferredWidth(60);
            cb_table.getColumnModel().getColumn(2).setMaxWidth(70);
            cb_table.getColumnModel().getColumn(3).setMinWidth(70);
            cb_table.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        cb_total_price.setText("Total Price:");

        cb_total_tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_total_tpriceActionPerformed(evt);
            }
        });

        cb_done.setText("Done");
        cb_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_total_price)
                .addGap(18, 18, 18)
                .addComponent(cb_total_tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_done)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_total_tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_total_price)
                    .addComponent(cb_done))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_total_tpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_total_tpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_total_tpriceActionPerformed

    private void cb_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_doneActionPerformed
        dispose();
    }//GEN-LAST:event_cb_doneActionPerformed
    public void setbill(int pid, String pname, float pqty, float pprice,float totalprice)
    {
        
        
        DefaultTableModel model=(DefaultTableModel)cb_table.getModel();
       
        model.addRow(new Object[]{pid,pname,pqty,pprice});
        cb_total_tprice.setText(Float.toString(totalprice));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cb_done;
    private javax.swing.JTable cb_table;
    private javax.swing.JLabel cb_total_price;
    private javax.swing.JTextField cb_total_tprice;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
