/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package supermarket;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Romil Chauhan
 */
public class LoggedIn extends javax.swing.JFrame {
    public float csum=0;
    public float ssum=0;
    public float to=0;
    /**
     * Creates new form LoggedIn
     */
    public LoggedIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StockDetails = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        s_pro_qty = new javax.swing.JLabel();
        s_pro_id = new javax.swing.JLabel();
        s_pro_tqty = new javax.swing.JTextField();
        s_pro_price = new javax.swing.JLabel();
        s_submit = new javax.swing.JButton();
        s_sup_name = new javax.swing.JLabel();
        s_sup_tname = new javax.swing.JTextField();
        s_pro_tprice = new javax.swing.JTextField();
        s_pro_tid = new javax.swing.JTextField();
        s_pro_name = new javax.swing.JLabel();
        s_pro_tname = new javax.swing.JTextField();
        s_pro_od = new javax.swing.JLabel();
        s_pro_tod = new javax.swing.JTextField();
        s_pro_dd = new javax.swing.JLabel();
        s_pro_tdd = new javax.swing.JTextField();
        s_total = new javax.swing.JButton();
        s_ttotal = new javax.swing.JTextField();
        s_ani = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        s_table = new javax.swing.JTable();
        s_reset = new javax.swing.JButton();
        s_confirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        c_total = new javax.swing.JButton();
        c_ttotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        c_pro_tid = new javax.swing.JTextField();
        c_pro_tname = new javax.swing.JTextField();
        c_pro_qty = new javax.swing.JLabel();
        javax.swing.JLabel c_pro_id = new javax.swing.JLabel();
        c_pro_tprice = new javax.swing.JTextField();
        c_pro_tqty = new javax.swing.JTextField();
        c_pro_name = new javax.swing.JLabel();
        c_pro_price = new javax.swing.JLabel();
        c_submit = new javax.swing.JButton();
        c_reset = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        c_table = new javax.swing.JTable();
        c_printbill = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sd_pro_ename = new javax.swing.JLabel();
        sd_pro_etname = new javax.swing.JTextField();
        sd_submit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sd_reset = new javax.swing.JButton();
        sd_pro_tqty = new javax.swing.JTextField();
        sd_pro_qty = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        to_pro_id = new javax.swing.JLabel();
        to_pro_tid = new javax.swing.JTextField();
        to_pro_name = new javax.swing.JLabel();
        to_pro_tname = new javax.swing.JTextField();
        to_submit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        to_table = new javax.swing.JTable();
        to_ttto = new javax.swing.JTextField();
        to_reset = new javax.swing.JButton();
        to_ti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        s_pro_qty.setText("Qty:");

        s_pro_id.setText("Product ID:");

        s_pro_price.setText("Price:");

        s_submit.setText("Submit");
        s_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_submitActionPerformed(evt);
            }
        });

        s_sup_name.setText("Supplier Name:");

        s_pro_tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_pro_tpriceActionPerformed(evt);
            }
        });

        s_pro_tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_pro_tidActionPerformed(evt);
            }
        });

        s_pro_name.setText("Product Name:");

        s_pro_od.setText("Order Date:");

        s_pro_tod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_pro_todActionPerformed(evt);
            }
        });

        s_pro_dd.setText("Delivery Date:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(s_pro_od)
                        .addGap(32, 32, 32)
                        .addComponent(s_pro_tod))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(s_sup_name)
                        .addGap(18, 18, 18)
                        .addComponent(s_sup_tname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(s_pro_qty)
                        .addGap(70, 70, 70)
                        .addComponent(s_pro_tqty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s_pro_id)
                .addGap(18, 18, 18)
                .addComponent(s_pro_tid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s_pro_price)
                            .addComponent(s_pro_dd))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(s_pro_tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(s_pro_tdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(s_pro_name)
                        .addGap(18, 18, 18)
                        .addComponent(s_pro_tname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(s_submit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_pro_tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_pro_name)
                    .addComponent(s_pro_tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_pro_id)
                    .addComponent(s_sup_tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_sup_name))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_pro_price)
                    .addComponent(s_pro_qty)
                    .addComponent(s_pro_tqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_pro_tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_pro_od)
                    .addComponent(s_pro_tod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_pro_tdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_pro_dd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(s_submit))
        );

        s_total.setText("Total:");
        s_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_totalActionPerformed(evt);
            }
        });

        s_ani.setText("Add new item");
        s_ani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_aniActionPerformed(evt);
            }
        });

        s_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name", "Product ID", "Product Name", "Qty", "Price", "Order Date", "Delivery Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(s_table);
        if (s_table.getColumnModel().getColumnCount() > 0) {
            s_table.getColumnModel().getColumn(3).setMinWidth(60);
            s_table.getColumnModel().getColumn(3).setPreferredWidth(60);
            s_table.getColumnModel().getColumn(3).setMaxWidth(60);
            s_table.getColumnModel().getColumn(4).setMinWidth(60);
            s_table.getColumnModel().getColumn(4).setPreferredWidth(60);
            s_table.getColumnModel().getColumn(4).setMaxWidth(60);
            s_table.getColumnModel().getColumn(5).setMinWidth(100);
            s_table.getColumnModel().getColumn(5).setPreferredWidth(100);
            s_table.getColumnModel().getColumn(5).setMaxWidth(100);
            s_table.getColumnModel().getColumn(6).setMinWidth(100);
            s_table.getColumnModel().getColumn(6).setPreferredWidth(100);
            s_table.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        s_reset.setText("Reset");
        s_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_resetActionPerformed(evt);
            }
        });

        s_confirm.setText("Confirm");
        s_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(s_total)
                .addGap(18, 18, 18)
                .addComponent(s_ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s_confirm)
                .addGap(18, 18, 18)
                .addComponent(s_reset)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(s_ani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s_ani)
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_total)
                    .addComponent(s_ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_confirm)
                    .addComponent(s_reset))
                .addGap(28, 28, 28))
        );

        StockDetails.addTab("Supplier Bill", jPanel2);

        c_total.setText("Total:");
        c_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_totalActionPerformed(evt);
            }
        });

        c_ttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ttotalActionPerformed(evt);
            }
        });

        c_pro_tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pro_tidActionPerformed(evt);
            }
        });

        c_pro_qty.setText("Qty:");

        c_pro_id.setText("Product ID:");

        c_pro_tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pro_tpriceActionPerformed(evt);
            }
        });

        c_pro_name.setText("Product Name:");

        c_pro_price.setText("Price:");

        c_submit.setText("Submit");
        c_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_pro_qty)
                    .addComponent(c_pro_id))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_pro_tqty, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(c_pro_tid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_pro_name)
                    .addComponent(c_pro_price))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_pro_tname, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(c_pro_tprice))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c_submit)
                .addGap(249, 249, 249))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pro_id)
                    .addComponent(c_pro_name)
                    .addComponent(c_pro_tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_pro_tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pro_qty)
                    .addComponent(c_pro_price)
                    .addComponent(c_pro_tqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_pro_tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c_submit)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        c_reset.setText("Reset");
        c_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_resetActionPerformed(evt);
            }
        });

        c_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(c_table);
        if (c_table.getColumnModel().getColumnCount() > 0) {
            c_table.getColumnModel().getColumn(0).setResizable(false);
            c_table.getColumnModel().getColumn(1).setResizable(false);
            c_table.getColumnModel().getColumn(1).setPreferredWidth(100);
            c_table.getColumnModel().getColumn(2).setPreferredWidth(30);
            c_table.getColumnModel().getColumn(3).setResizable(false);
        }

        c_printbill.setText("Print Bill");
        c_printbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_printbillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(c_total)
                .addGap(18, 18, 18)
                .addComponent(c_ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c_printbill)
                .addGap(18, 18, 18)
                .addComponent(c_reset)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_total)
                    .addComponent(c_ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_printbill)
                    .addComponent(c_reset))
                .addGap(30, 30, 30))
        );

        StockDetails.addTab("Customer Bill", jPanel1);

        sd_pro_ename.setText("Product Name:");

        sd_pro_etname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_pro_etnameActionPerformed(evt);
            }
        });

        sd_submit.setText("Submit");
        sd_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_submitActionPerformed(evt);
            }
        });

        sd_reset.setText("Reset");
        sd_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_resetActionPerformed(evt);
            }
        });

        sd_pro_tqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_pro_tqtyActionPerformed(evt);
            }
        });

        sd_pro_qty.setText("Quantity Reamining:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sd_pro_qty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(sd_pro_tqty, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(sd_reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sd_pro_qty)
                    .addComponent(sd_pro_tqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sd_reset)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(sd_pro_ename)
                .addGap(18, 18, 18)
                .addComponent(sd_pro_etname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(sd_submit)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sd_pro_ename)
                    .addComponent(sd_pro_etname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sd_submit))
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        StockDetails.addTab("Stock Details", jPanel3);

        to_pro_id.setText("Product ID:");

        to_pro_name.setText("Product Name:");

        to_submit.setText("Submit");
        to_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_submitActionPerformed(evt);
            }
        });

        to_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Cost Price", "Selling Price", "Quantity Sold", "Product Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(to_table);
        if (to_table.getColumnModel().getColumnCount() > 0) {
            to_table.getColumnModel().getColumn(0).setMinWidth(75);
            to_table.getColumnModel().getColumn(1).setMinWidth(75);
            to_table.getColumnModel().getColumn(2).setMinWidth(75);
            to_table.getColumnModel().getColumn(3).setMinWidth(75);
            to_table.getColumnModel().getColumn(4).setMinWidth(75);
            to_table.getColumnModel().getColumn(5).setMinWidth(75);
        }

        to_ttto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_tttoActionPerformed(evt);
            }
        });

        to_reset.setText("Reset");
        to_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_resetActionPerformed(evt);
            }
        });

        to_ti.setText("Total Income:");
        to_ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_tiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(to_pro_id)
                .addGap(18, 18, 18)
                .addComponent(to_pro_tid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(to_pro_name)
                .addGap(18, 18, 18)
                .addComponent(to_pro_tname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(to_submit)
                .addGap(40, 40, 40))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(to_ti)
                .addGap(18, 18, 18)
                .addComponent(to_ttto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(to_reset)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to_pro_id)
                    .addComponent(to_pro_tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_pro_name)
                    .addComponent(to_pro_tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_submit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to_ti)
                    .addComponent(to_ttto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_reset))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        StockDetails.addTab("Turn Over", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StockDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(StockDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_pro_tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_pro_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_pro_tidActionPerformed

    private void s_pro_tpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_pro_tpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_pro_tpriceActionPerformed

    private void s_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_totalActionPerformed
        s_ttotal.setText(Float.toString(ssum));
    }//GEN-LAST:event_s_totalActionPerformed

    private void sd_pro_etnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_pro_etnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_pro_etnameActionPerformed

    private void c_pro_tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pro_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pro_tidActionPerformed

    private void c_pro_tpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pro_tpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pro_tpriceActionPerformed

    private void c_ttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ttotalActionPerformed

    private void c_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_submitActionPerformed
        
        int pid=Integer.parseInt(c_pro_tid.getText());
        String pname=c_pro_tname.getText();
        float pqty=Float.parseFloat(c_pro_tqty.getText());
        float pprice=Float.parseFloat(c_pro_tprice.getText());
        float tprice=pqty*pprice;
        
        csum+=tprice;
        
        DefaultTableModel model=(DefaultTableModel)c_table.getModel();
       
        model.addRow(new Object[]{pid,pname,pqty,pprice});
        
        c_pro_tid.setText("");
        c_pro_tname.setText("");
        c_pro_tprice.setText("");
        c_pro_tqty.setText("");
        
    }//GEN-LAST:event_c_submitActionPerformed

    private void c_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_totalActionPerformed
        c_ttotal.setText(Float.toString(csum));
    }//GEN-LAST:event_c_totalActionPerformed

    private void c_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_resetActionPerformed
       csum=0;
       c_ttotal.setText(Float.toString(csum));
       while(c_table.getRowCount()>0)
       {((DefaultTableModel) c_table.getModel()).removeRow(0);}
    }//GEN-LAST:event_c_resetActionPerformed

    private void s_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_resetActionPerformed
        ssum=0;
       s_ttotal.setText(Float.toString(ssum));
       while(s_table.getRowCount()>0)
       {((DefaultTableModel) s_table.getModel()).removeRow(0);}
    }//GEN-LAST:event_s_resetActionPerformed

    private void s_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_submitActionPerformed
        int pid=Integer.parseInt(s_pro_tid.getText());
        String pname=s_pro_tname.getText();
        String sname=s_sup_tname.getText();
        float pqty=Float.parseFloat(s_pro_tqty.getText());
        float pprice=Float.parseFloat(s_pro_tprice.getText());
        float tprice=pqty*pprice;
        
        ssum+=tprice;
        String od=s_pro_tod.getText();
        String dd=s_pro_tdd.getText();
        DefaultTableModel model=(DefaultTableModel)s_table.getModel();
       
        model.addRow(new Object[]{sname,pid,pname,pqty,pprice,od,dd});
        s_sup_tname.setText("");
        s_pro_tid.setText("");
        s_pro_tname.setText("");
        s_pro_tprice.setText("");
        s_pro_tqty.setText("");
        s_pro_tod.setText("");
        s_pro_tdd.setText("");
    }//GEN-LAST:event_s_submitActionPerformed

    private void s_aniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_aniActionPerformed
        AddNewItem ani=new AddNewItem();
        ani.setVisible(true);
    }//GEN-LAST:event_s_aniActionPerformed

    private void s_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_confirmActionPerformed
        dbconnect dbs_confirm=new dbconnect();
        int x=s_table.getRowCount();
        
        int i=0;
        while(i!=x)
        {
            String sname=(String) s_table.getModel().getValueAt(i, 0);
            int pid=(int) s_table.getModel().getValueAt(i, 1);
            String pname=(String) s_table.getModel().getValueAt(i, 2);
            float pqty=(float) s_table.getModel().getValueAt(i, 3);
            float pprice=(float) s_table.getModel().getValueAt(i, 4);
            String od=(String) s_table.getModel().getValueAt(i, 5);
            String dd=(String) s_table.getModel().getValueAt(i, 6);
            float tprice=pqty*pprice;
            
            
            
            try {
                dbs_confirm.addsup(sname,pid,pname,pqty,pprice,tprice,od,dd);
            } catch (SQLException ex) {
                Logger.getLogger(LoggedIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
            
        }
        
        
    }//GEN-LAST:event_s_confirmActionPerformed

    private void s_pro_todActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_pro_todActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_pro_todActionPerformed

    private void c_printbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_printbillActionPerformed
        
        dbconnect b=new dbconnect();
        CustomerBill cb=new CustomerBill();
        cb.setVisible(true);

        int x=c_table.getRowCount();
        float print_bill_totalprice=Float.parseFloat(c_ttotal.getText());
        int i=0;
        while(i!=x)
        {
            int pid=(int) c_table.getModel().getValueAt(i, 0);
            String pname=(String) c_table.getModel().getValueAt(i, 1);
            float pqty=(float) c_table.getModel().getValueAt(i, 2);
            float pprice=(float) c_table.getModel().getValueAt(i, 3);
            try {
                b.addbill(pid,pname,pqty,pprice);
            } catch (SQLException ex) {
                Logger.getLogger(LoggedIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            cb.setbill(pid,pname,pqty,pprice,print_bill_totalprice);

            i++;
        }
        
    }//GEN-LAST:event_c_printbillActionPerformed

    private void sd_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_submitActionPerformed
        dbconnect dbsd=new dbconnect();
        String pname=sd_pro_etname.getText();
        //int pid=Integer.parseInt(sd_pro_etid.getText());
        
       
            
        try {
            float qty=dbsd.getsd(pname);
            sd_pro_tqty.setText(Float.toString(qty));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_sd_submitActionPerformed

    private void sd_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_resetActionPerformed
       //sd_pro_etid.setText("");
        sd_pro_etname.setText("");
        sd_pro_tqty.setText("");
    }//GEN-LAST:event_sd_resetActionPerformed

    private void sd_pro_tqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_pro_tqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_pro_tqtyActionPerformed

    private void to_tttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_tttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_tttoActionPerformed

    private void to_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_submitActionPerformed
        dbconnect dbto=new dbconnect();
            int pid=Integer.parseInt(to_pro_tid.getText());
            String pname=to_pro_tname.getText();
        
        try {         
            float pcp=dbto.getcp(pid);
            float psp=dbto.getsp(pid);
            float pqs=dbto.getqs(pid);
                        
            float pto=(psp-pcp)*pqs;
            
            
            
            DefaultTableModel model=(DefaultTableModel)to_table.getModel();
       
            model.addRow(new Object[]{pid,pname,pcp,psp,pqs,pto});
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LoggedIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_to_submitActionPerformed

    private void to_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_resetActionPerformed
       to_pro_tid.setText("");
       to_pro_tname.setText("");
       to_ttto.setText("");
       while(to_table.getRowCount()>0)
       {((DefaultTableModel) to_table.getModel()).removeRow(0);}
    }//GEN-LAST:event_to_resetActionPerformed

    private void to_tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_tiActionPerformed
        dbconnect db =new dbconnect();
          try{  
            to=db.dbupdateto();
            to_ttto.setText(Float.toString(to));
           } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_to_tiActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane StockDetails;
    private javax.swing.JButton c_printbill;
    private javax.swing.JLabel c_pro_name;
    private javax.swing.JLabel c_pro_price;
    private javax.swing.JLabel c_pro_qty;
    private javax.swing.JTextField c_pro_tid;
    private javax.swing.JTextField c_pro_tname;
    private javax.swing.JTextField c_pro_tprice;
    private javax.swing.JTextField c_pro_tqty;
    private javax.swing.JButton c_reset;
    private javax.swing.JButton c_submit;
    private javax.swing.JTable c_table;
    private javax.swing.JButton c_total;
    private javax.swing.JTextField c_ttotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton s_ani;
    private javax.swing.JButton s_confirm;
    private javax.swing.JLabel s_pro_dd;
    private javax.swing.JLabel s_pro_id;
    private javax.swing.JLabel s_pro_name;
    private javax.swing.JLabel s_pro_od;
    private javax.swing.JLabel s_pro_price;
    private javax.swing.JLabel s_pro_qty;
    private javax.swing.JTextField s_pro_tdd;
    private javax.swing.JTextField s_pro_tid;
    private javax.swing.JTextField s_pro_tname;
    private javax.swing.JTextField s_pro_tod;
    private javax.swing.JTextField s_pro_tprice;
    private javax.swing.JTextField s_pro_tqty;
    private javax.swing.JButton s_reset;
    private javax.swing.JButton s_submit;
    private javax.swing.JLabel s_sup_name;
    private javax.swing.JTextField s_sup_tname;
    private javax.swing.JTable s_table;
    private javax.swing.JButton s_total;
    private javax.swing.JTextField s_ttotal;
    private javax.swing.JLabel sd_pro_ename;
    private javax.swing.JTextField sd_pro_etname;
    private javax.swing.JLabel sd_pro_qty;
    private javax.swing.JTextField sd_pro_tqty;
    private javax.swing.JButton sd_reset;
    private javax.swing.JButton sd_submit;
    private javax.swing.JLabel to_pro_id;
    private javax.swing.JLabel to_pro_name;
    private javax.swing.JTextField to_pro_tid;
    private javax.swing.JTextField to_pro_tname;
    private javax.swing.JButton to_reset;
    private javax.swing.JButton to_submit;
    private javax.swing.JTable to_table;
    private javax.swing.JButton to_ti;
    private javax.swing.JTextField to_ttto;
    // End of variables declaration//GEN-END:variables

    

    
}
